# Nombre de tu aplicación
spring.application.name=sistema-gestion

# Configuración de la conexión a PostgreSQL
# Si al instalar Postgres no cambiaste el puerto, es el 5432
spring.datasource.url=jdbc:postgresql://localhost:5432/elsur_imprenta
spring.datasource.username=postgres
spring.datasource.password=2628

# Estrategia de actualización de la base de datos
# 'update' hace que Hibernate cree las tablas automáticamente según tus clases Java
spring.jpa.hibernate.ddl-auto=update


logging.level.org.springframework.security=DEBUG

# Mostrar las consultas SQL en la consola (muy útil para aprender)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect